/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2018  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.18.0
 * from project D:/Projects/sw.Baukasten.LowRangeOs/applications/eval_app_canopen/src/objdic/objdic.can
 * on 2020/04/09 at 16:48:53.
 */

/**
 * \file objects.h
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1



/* Declaration of Variables (Maintenance) */

extern CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32 p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8 p301_error_register;
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[18];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[3];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[13];
extern CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T p301_identity;
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern VALUE_DESC_T CO_CONST i1000_desc[1];
extern VALUE_DESC_T CO_CONST i1001_desc[1];
extern VALUE_DESC_T CO_CONST i1008_desc[1];
extern VALUE_DESC_T CO_CONST i1009_desc[1];
extern VALUE_DESC_T CO_CONST i100A_desc[1];
extern VALUE_DESC_T CO_CONST i1017_desc[1];
extern VALUE_DESC_T CO_CONST i1018_desc[5];
#endif /* CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern OBJDIR_T objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

