/*
 * objects.c - Object dictionary
 *
 * Copyright (C) 1998-2018  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.18.0
 * from project D:/Projects/sw.Baukasten.LowRangeOs/applications/eval_app_canopen/src/objdic/objdic.can
 * on 2020/04/09 at 16:48:53.
 */

/**
 * \file objects.c
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#define OBJECTS_C 1
#include <stdlib.h>
#include <cal_conf.h>      /* !!! first file to include for all CANopen */
#include <co_acces.h>
#include <co_pdo.h>
#include <co_sdo.h>
#include <co_stru.h>
#include <string.h>
#include <co_mcpy.h>
#include <objects.h>
/*  number of entries in the object dictionary */
CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements = 7;

/*  Definition of Variables (Device Objects)  */
CO_DT_INIT_VAR UNSIGNED32 p301_device_type = { 0x00000000UL };
CO_DT_INIT_VAR UNSIGNED8 p301_error_register = { 0x00 };
CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[18] = { "STM Nucleo L432KC" };
CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[3] = { "01" };
CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[13] = { "VA001 Zephyr" };
CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time = { 0x00000BB8 };
CO_DT_INIT_VAR IDENTITY_T p301_identity = { 0x4, 0x53UL, 0x0UL, 0x01UL,
    0xa01UL };



/* Default values */
CO_CONST UNSIGNED8 l0_default1_0005[2] = { 0x0, 0x4 };
CO_CONST OCT_STRING_T l0_default1_000A[3] = { 0x12, 0x3, 0xd };
CO_CONST UNSIGNED16 l0_default1_0006[1] = { 0xbb8 };
CO_CONST UNSIGNED32 l0_default1_0007[4] = { 0x0UL, 0x53UL, 0x1UL,
    0xa01UL };
CO_CONST STRING_DATA_T l0_string_data_1[3] = {{0x12, 0x12}, {0x3, 0x3},
    {0xd, 0xd}};

/* Limits */
#ifdef CONFIG_LIMITS_CHECK
CO_CONST LIMIT_U8_T l0_limits1_0005[2] = { {0x0, 0xff}, {0x1, 0x4} };
CO_CONST LIMIT_U16_T l0_limits1_0006[1] = { {0x0, 0xffff} };
CO_CONST LIMIT_U32_T l0_limits1_0007[1] = { {0x0UL, 0xffffffffUL} };
#endif /* CONFIG_LIMITS_CHECK */


/*  Definition of Value Descriptions  */
VALUE_DESC_T CO_CONST  i1000_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_CONST_PERM | CO_READ_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  i1001_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  i1008_desc[1] =  {
    { (UNSIGNED8 *) &l0_string_data_1[0],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_CONST_PERM | CO_READ_PERM }
    };
VALUE_DESC_T CO_CONST  i1009_desc[1] =  {
    { (UNSIGNED8 *) &l0_string_data_1[1],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_CONST_PERM | CO_READ_PERM }
    };
VALUE_DESC_T CO_CONST  i100A_desc[1] =  {
    { (UNSIGNED8 *) &l0_string_data_1[2],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_CONST_PERM | CO_READ_PERM }
    };
VALUE_DESC_T CO_CONST  i1017_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0006[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  i1018_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0005[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

/* Definition of the object directory */
OBJDIR_T objDir[] = {
{   (UNSIGNED8 *)&p301_device_type,
    (VALUE_DESC_T *)i1000_desc,
    0x1000, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_error_register,
    (VALUE_DESC_T *)i1001_desc,
    0x1001, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)p301_manu_device_name,
    (VALUE_DESC_T *)i1008_desc,
    0x1008, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)p301_manu_hardware_version,
    (VALUE_DESC_T *)i1009_desc,
    0x1009, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)p301_manu_software_version,
    (VALUE_DESC_T *)i100A_desc,
    0x100A, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_prod_hb_time,
    (VALUE_DESC_T *)i1017_desc,
    0x1017, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_identity,
    (VALUE_DESC_T *)i1018_desc,
    0x1018, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    }
};
