# Keep caches enabled when jumping to app
CONFIG_BOOT_DISABLE_CACHES=n
# Clean up interrupts/MPU/caches before jumping to app
CONFIG_MCUBOOT_CLEANUP_ARM_CORE=y
# Don't start M4 from MCUboot
CONFIG_STM32H7_BOOT_M4_AT_INIT=n
